---
title: Nice Tapes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
  tapes:
    title: tapes
    output: true
defaults:
- scope:
    path: tapes
    type: posts
  values:
    title: ''
    layout: default
    number: ''
    year: ''
    link: ''
    tracklist: ''
